// Example cases for the console's mock mode (P4), in CaseDetail's shape: the demo story's fire report next
// to Gurpreet's farm in Sangrur with his open help request, Kisan's own help case, a garbage fire in Patiala,
// and a report with a photo that didn't match its upload.
import type { components } from '../../../packages/contracts/types';

type CaseDetail = components['schemas']['CaseDetail'];

const gurpreet = {
  id: 'kisan-3f9c2a',
  farmerId: 'kisan-farmer-3f9c2a',
  farmLocation: { lat: 30.266, lon: 76.04 },
  district: 'Sangrur',
  crop: 'Paddy',
  acreage: 18,
  machineType: 'Happy Seeder',
  requiredFrom: '2026-10-20T00:00:00+05:30',
  requiredUntil: '2026-11-09T00:00:00+05:30',
  coveragePercent: 92,
  uncoveredAcres: 1.5,
  status: 'OPEN' as const,
};

const chcC = {
  id: 'demo-chc-c:happy_seeder',
  chcId: 'demo-chc-c',
  chcName: 'Demo CHC C (25 km away)',
  location: { lat: 30.041, lon: 76.04 },
  machineType: 'Happy Seeder',
  availableFrom: '2026-10-20T00:00:00+05:30',
  availableUntil: '2026-11-09T00:00:00+05:30',
  status: 'AVAILABLE' as const,
};

const reason = (near: string) =>
  `Open help request ${near}1.5 acres still need a Happy Seeder. Happy Seeder free at Demo CHC C (25 km away) (25 km) from 2026-10-20: send it before any penalty.`;

export const MOCK_CASES: CaseDetail[] = [
  {
    case: {
      id: 'case-demo-fire',
      incidentReportId: 'complaint-demo-fire',
      verificationStatus: 'UNVERIFIED',
      helpRequestId: gurpreet.id,
      recommendedMachineId: chcC.id,
      evidenceSummary: '1 file: 1 matches its upload hash',
      recommendationReason: reason('470 m from the report. '),
      status: 'OPEN',
      version: 1,
      createdAt: '2026-10-09T14:02:00+05:30',
      updatedAt: '2026-10-09T14:02:00+05:30',
    },
    type: 'farm_fire',
    penalty: true,
    authorities: ['SDM', 'District Agriculture Officer'],
    deadline: '2026-10-09T18:02:00+05:30',
    report: {
      id: 'complaint-demo-fire',
      reportedAt: '2026-10-09T14:00:00+05:30',
      reporterId: 'anonymous',
      location: { lat: 30.2624, lon: 76.0425 },
      description: 'Thick smoke from the paddy field by the canal, visible from the main road.',
      district: 'Sangrur',
      status: 'OPEN',
    },
    helpRequest: gurpreet,
    helpLink: { distanceMeters: 466, ambiguous: false },
    recommendedMachine: chcC,
    decisions: [],
  },
  {
    case: {
      id: 'case-demo-help',
      incidentReportId: 'complaint-demo-help',
      verificationStatus: 'UNVERIFIED',
      helpRequestId: gurpreet.id,
      recommendedMachineId: chcC.id,
      evidenceSummary: 'No files attached',
      recommendationReason: reason(''),
      status: 'OPEN',
      version: 1,
      createdAt: '2026-10-09T11:20:00+05:30',
      updatedAt: '2026-10-09T11:20:00+05:30',
    },
    type: 'farmer_support',
    penalty: false,
    authorities: ['Agriculture department', 'CHC'],
    deadline: '2026-10-11T11:20:00+05:30',
    report: {
      id: 'complaint-demo-help',
      reportedAt: '2026-10-09T11:18:00+05:30',
      reporterId: 'kisan_saathi',
      location: gurpreet.farmLocation,
      description: '',
      district: 'Sangrur',
      status: 'OPEN',
    },
    helpRequest: gurpreet,
    recommendedMachine: chcC,
    decisions: [],
  },
  {
    case: {
      id: 'case-demo-garbage',
      incidentReportId: 'complaint-demo-garbage',
      verificationStatus: 'UNVERIFIED',
      evidenceSummary: '2 files: 2 match their upload hash',
      status: 'OPEN',
      version: 1,
      createdAt: '2026-10-09T09:40:00+05:30',
      updatedAt: '2026-10-09T09:40:00+05:30',
    },
    type: 'garbage',
    penalty: true,
    authorities: ['Municipal Corporation'],
    deadline: '2026-10-10T09:40:00+05:30',
    report: {
      id: 'complaint-demo-garbage',
      reportedAt: '2026-10-09T09:38:00+05:30',
      reporterId: 'anonymous',
      location: { lat: 30.3398, lon: 76.3869 },
      description: 'Garbage burning behind the bus stand every morning.',
      district: 'Patiala',
      status: 'OPEN',
    },
    decisions: [],
  },
  {
    case: {
      id: 'case-demo-review',
      incidentReportId: 'complaint-demo-review',
      verificationStatus: 'NEEDS_REVIEW',
      evidenceSummary: "1 file: 1 doesn't match its hash",
      status: 'OPEN',
      version: 1,
      createdAt: '2026-10-09T13:15:00+05:30',
      updatedAt: '2026-10-09T13:15:00+05:30',
    },
    type: 'farm_fire',
    penalty: true,
    authorities: ['SDM', 'District Agriculture Officer'],
    deadline: '2026-10-09T17:15:00+05:30',
    report: {
      id: 'complaint-demo-review',
      reportedAt: '2026-10-09T13:12:00+05:30',
      reporterId: 'anonymous',
      location: { lat: 30.62, lon: 75.62 },
      description: 'Fire near the village pond.',
      district: 'unassigned',
      status: 'OPEN',
    },
    decisions: [],
  },
];
