// Kisan Saathi (P1) files help requests from Python. These examples are generated by
// services/agent-kisan (python -m agent_kisan.contract_fixtures); if this test fails, the
// two sides of the HelpRequest contract have drifted apart.
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { HelpRequestSchema } from "../domain/schemas";

const examples: Record<string, Record<string, unknown>> = JSON.parse(
  readFileSync(join(__dirname, "../../packages/contracts/fixtures/kisan-help-requests.json"), "utf8"),
);

describe("Kisan Saathi help requests", () => {
  it.each(Object.entries(examples))("%s matches HelpRequestSchema", (_name, example) => {
    const result = HelpRequestSchema.safeParse(example);
    expect(result.error?.issues ?? []).toEqual([]);
  });

  it("Gurpreet's request is open for the 1.5 acres the plan could not book", () => {
    const request = HelpRequestSchema.parse(examples.gurpreet_open);
    expect(request.status).toBe("OPEN");
    expect(request.uncoveredAcres).toBe(1.5);
    expect(request.machineType).toBe("Happy Seeder");
  });

  it("a fully booked plan is MATCHED with nothing uncovered", () => {
    const request = HelpRequestSchema.parse(examples.fully_booked_matched);
    expect(request.status).toBe("MATCHED");
    expect(request.uncoveredAcres).toBe(0);
  });
});
